[package]
name = "vk_execute_compiler"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "VK execute compiler"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vk_method = "0.1"
serde_json = "1.0"
ijson = "0.1.3"
